# Generated by Django 3.1.7 on 2021-04-21 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo_marca', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BrandReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=150)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('delete_at', models.DateTimeField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobile.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.IntegerField()),
                ('color', models.CharField(max_length=150)),
                ('clase', models.CharField(max_length=150)),
                ('numero_chasis', models.CharField(max_length=150)),
                ('numero_motor', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=150)),
                ('placa', models.CharField(max_length=150)),
                ('kilometraje', models.IntegerField()),
                ('cilindraje', models.IntegerField()),
                ('tipo_combustible', models.CharField(max_length=150)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('delete_at', models.DateTimeField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobile.brand')),
                ('reference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobile.brandreference')),
            ],
        ),
    ]
